# Generated by Django 5.0.1 on 2024-01-04 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('especialidade', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=60)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_final', models.DateTimeField()),
                ('local', models.CharField(max_length=60)),
                ('medico', models.CharField(max_length=60)),
                ('qtd_pacientes', models.IntegerField()),
                ('data_entrega', models.DateField()),
                ('local_entrega_oculos', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('medicos', models.ManyToManyField(to='campanha.medico', verbose_name='lista de medicos')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha', models.CharField(max_length=60)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanha.campanha', verbose_name='a campanha relacionada')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('nome_responsavel', models.CharField(max_length=60)),
                ('nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=11)),
                ('obs', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('confirmado', models.BooleanField()),
                ('tem_receita', models.BooleanField()),
                ('quem_indicou', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tickets', models.ManyToManyField(to='campanha.ticket', verbose_name='lista de tickets')),
            ],
        ),
    ]
