# Generated by Django 5.0.1 on 2024-01-04 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanha',
            name='medico',
        ),
    ]
