# Generated by Django 5.0.1 on 2024-01-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0002_remove_campanha_medico'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paciente',
            new_name='Participante',
        ),
        migrations.RenameField(
            model_name='campanha',
            old_name='qtd_pacientes',
            new_name='qtd_participantes',
        ),
        migrations.AlterField(
            model_name='campanha',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='medicos',
            field=models.ManyToManyField(to='campanha.medico', verbose_name='medicos responsáveis'),
        ),
    ]
