# Generated by Django 5.0.1 on 2024-01-20 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0003_rename_paciente_participante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='tickets',
        ),
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=60)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanha.campanha', verbose_name='a campanha relacionada')),
            ],
        ),
        migrations.AddField(
            model_name='participante',
            name='chaves',
            field=models.ManyToManyField(to='campanha.chave', verbose_name='lista de chaves'),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
