# Generated by Django 5.0.1 on 2024-01-22 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0004_remove_participante_tickets_chave_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chave',
            options={'permissions': [('generate_chave', 'Can generate chave')]},
        ),
    ]
