# Generated by Django 5.0.1 on 2024-01-24 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0005_alter_chave_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='chaves',
        ),
        migrations.AddField(
            model_name='chave',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campanha.participante', verbose_name='O participante relacionado'),
        ),
    ]
